development:
  database: user_upload_development
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: password
  pool: 5
  template: template0

test:
  adapter: postgresql
  encoding: utf8
  database: user_upload_test
  pool: 5
  username: postgres
  password: password
  min_messages: WARNING
  host: localhost
  template: template0

